version: "2"
services:
    api:
        image: "ionutindre/rock_paper_scissors_lizard_spock_game:dev"
        ports:
            - "8000:80"
            - "8080:443"
        depends_on:
            - db
        environment:
          ASPNETCORE_URLS: "http://+:80;https://+:443"
          ASPNETCORE_ENVIRONMENT: "Development"
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"